---
- name: Apply Vlan Configuration templates
  hosts: all
  connection: network_cli
  gather_facts: no
  tasks:
    - name: Build Config Templates for Vlan Creation/Removal
      template:
        src: "{{ template_name }}"
        dest: /var/tmp/{{ inventory_hostname }}.conf

    - name: Push Dell OS 9 Config
      sense.dellos9.dellos9_config:
        src: /var/tmp/{{ inventory_hostname }}.conf
        save: yes
        provider:
          host: "{{ ansible_host }}"
          timeout: 300
      when: ansible_network_os is defined and ansible_network_os == 'sense.dellos9.dellos9'

    - name: Push Dell OS 10 Config
      sense.dellos10.dellos10_config:
        src: /var/tmp/{{ inventory_hostname }}.conf
        save: yes
        provider:
          host: "{{ ansible_host }}"
          timeout: 300
      when: ansible_network_os is defined and ansible_network_os == 'sense.dellos10.dellos10'

    - name: Push Arista EOS Config
      sense.aristaeos.aristaeos_config:
        src: /var/tmp/{{ inventory_hostname }}.conf
        running_config: "! Command: show running-config"
      when: ansible_network_os == "sense.aristaeos.aristaeos"

    - name: Push Cisco NX Config
      cisco.nxos.nxos_config:
        src: /var/tmp/{{ inventory_hostname }}.conf
        running_config: "! Command: show running-config"
      when: ansible_network_os == "cisco.nxos.nxos"

    - name: Transfer Sonic Script
      copy: src=scripts/sonic.py dest=/var/tmp/sonic.py mode=0755
      when: ansible_network_os is defined and ansible_network_os == "sonic"

    - name: Apply Config on Azure Sonic
      command: python3 /var/tmp/sonic.py --config /var/tmp/{{ inventory_hostname }}.conf
      when: ansible_network_os is defined and ansible_network_os == "sonic"
    #- name: Remove the config files
    #  file: path="/var/tmp/{{ inventory_hostname }}.conf" state=absent
